In [2]:
import pandas as pd

In [3]:
# First DataFrame
df1 = pd.DataFrame({
    'ID': [1, 2],
    'Name': ['Aman', 'Riya']
})

# Second DataFrame
df2 = pd.DataFrame({
    'ID': [3, 4],
    'Name': ['Karan', 'Neha']
})

# Third DataFrame
df3 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Jaipur']
})

print("DataFrame 1")
print(df1)

print("\nDataFrame 2")
print(df2)

print("\nDataFrame 3")
print(df3)

DataFrame 1
   ID  Name
0   1  Aman
1   2  Riya

DataFrame 2
   ID   Name
0   3  Karan
1   4   Neha

DataFrame 3
   ID    City
0   1   Delhi
1   2  Mumbai
2   3    Pune
3   4  Jaipur

In [4]:
# Concatenate df1 and df2 vertically
concat_df = pd.concat([df1, df2], axis=0)

print("Concatenated DataFrame")
print(concat_df)

Concatenated DataFrame
   ID   Name
0   1   Aman
1   2   Riya
0   3  Karan
1   4   Neha

In [5]:
# Concatenate df1 and df2 horizontally
concat_df = pd.concat([df1, df3], axis=1)

print("Concatenated DataFrame")
print(concat_df)

Concatenated DataFrame
    ID  Name  ID    City
0  1.0  Aman   1   Delhi
1  2.0  Riya   2  Mumbai
2  NaN   NaN   3    Pune
3  NaN   NaN   4  Jaipur

In [6]:
concat_df = pd.concat([df1, df2], axis=0, ignore_index=True)

print(concat_df)

   ID   Name
0   1   Aman
1   2   Riya
2   3  Karan
3   4   Neha

In [7]:
merged_df = pd.merge(concat_df, df3, on='ID')

print("Merged DataFrame")
print(merged_df)

Merged DataFrame
   ID   Name    City
0   1   Aman   Delhi
1   2   Riya  Mumbai
2   3  Karan    Pune
3   4   Neha  Jaipur

In [9]:
pd.merge(concat_df, df3, on='ID', how='inner')

#Returns only matching rows.

   ID   Name    City
0   1   Aman   Delhi
1   2   Riya  Mumbai
2   3  Karan    Pune
3   4   Neha  Jaipur

In [10]:
pd.merge(concat_df, df3, on='ID', how='left')

#Keeps all rows from left DataFrame.

   ID   Name    City
0   1   Aman   Delhi
1   2   Riya  Mumbai
2   3  Karan    Pune
3   4   Neha  Jaipur

In [12]:
pd.merge(concat_df, df3, on='ID', how='right')

#Keeps all rows from right DataFrame.

   ID   Name    City
0   1   Aman   Delhi
1   2   Riya  Mumbai
2   3  Karan    Pune
3   4   Neha  Jaipur

In [13]:
pd.merge(concat_df, df3, on='ID', how='outer')

#Keeps all rows from both DataFrames.

   ID   Name    City
0   1   Aman   Delhi
1   2   Riya  Mumbai
2   3  Karan    Pune
3   4   Neha  Jaipur